---
title: "Making R Work in Government"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    mathjax: null
    theme: flatly
---

```{r setup, include=FALSE}
library(knitr)
library(flexdashboard)
```

CTQ Row
-----------------------------------------------------------------------

### 

#### Context

Data analysis is no longer confined to individuals working in isolation (was it ever?). Modern connectivity and complexity of problems requires teamwork, reproducibility and collaboration. Similarly, the analytic outputs must be actionable, understandable and intuitive such that wider communities can benefit from the results. 


#### Trigger

The 2024 Ihaka Lecture Series features three speakers that bring together experience in visualisation, teamwork and reproducibility. Today's talk is the third of the three and is focused on making R work in government.

#### Question

What has to be done to make R a critical component of the transformation of the effectiveness and efficiency of an analytical team in government?

<div id="answer" class="alert alert-info">
R's competitor in government is is not Julia or Python or SAS but Excel.The keys to making to the most of R are not the latest and fanciest R packages, but integrating it into a new workflow. That workflow also uses Git and SQL. It breaks down micro-silos and lone Excel geniuses, replacing them with teamwork, transparency, reproducible analytical pipelines, peer review, and home grown R packages and rules for use.
</div>


Storyline Row
-----------------------------------------------------------------------

### Analytics in government is often a mess

* The policy and program issues that need analysis are often massive in scope, the data is poor, and expectations are nearly always unrealistic.
* Managers often don't know what good looks like.
* Processes, systems and recruitment are usually a legacy hodge-podge.

### R is a great tool for analytics in government but it doesn't solve everything by itself

* We no longer need to worry about whether R has the right functionality, has corporate support, or is easy enough to learn;
* But slotting in a great tool for data manipulation, analysis and visualisation draws attention to other deficiencies.
* Typically those include data pipelines and management, data access and control, quality control, team work, statistical inference challenges, and statistical literacy of end users.
* This means the solution has to involve Git, databases, peer review, enshrining reproducibility as a fundamental principle, improving data governance, connecting better with policy and program teams, and basically changing the whole way we manage the data teams.
* One fault of the R community is a tendency to try to use R for everything. You should embrace instead a "best of breed" approach for each part of the pipeline.

### Change is hard, and making people do anything different in parallel with their day jobs is hard.

* Public sector work can appear to be hierarchical and disciplined but in fact getting anyone to do even basic things - like filing, using the right logo, sending decisions to the right people, or turning up to meetings - is surprisingly hard
* This makes an unsexy change like using Git particularly hard to implement
* People need time to learn, and to build things. It is particularly hard to build things when you are learning the concepts for the first time. 
* If people are already overloaded in their work they won't have time or brainspace to learn, and certainly not to build new things 
* Things will get worse before they get better and this is challenging in particularly public sector ways - low tolerance for failure.
* Success is only going to be at an institutional or team level, not at an individual level - but the success is made up of individuals.

### If you pay attention to change fundamentals, things can work out ok

* The fundamentals of any organisational change program apply
* Plan for change to take years not months
* People need to be persuaded. This is going to include both working-level people (who need to actually change how they work) and senior management (who need to allow time and resource to be used on change)
* But time somehow needs to be found for people to do the learning and building.
* A successful program will need lots of training, some turnover of staff, strong top-down direction, bottom-up support from peer champions, some externally facing wins (e.g. dashboard the Minister loves) to get cudos from the clients, and internally facing wins (e.g. suddenly easier to do something that was previously impossible) to get support from the staff
* Constantly remind people of the big picture vision
* Look for external demands (e.g. Ministerial demand for X) to leverage
* Work with your IT team, not against them
* Invest! - in databases, IT projects that mean you need less IT projects, in documentation, induction, training, R packages for repeat styles, analysis or data management tasks


